### ISSUE TITLE
Move-in and move-out date consistency

### ISSUE THREAD

**Issue by ghost** [scg-unibe-ch/ese2016-team8#1]
When creating an ad, one can set the move-in date and optionally also the move-out date, compare the following image:

![PlacingAnAd](https://cloud.githubusercontent.com/assets/15871260/19471975/a60b0d8a-9525-11e6-8d39-a999234085a5.jpeg)

**Although the move-out date is before the move-in date, I can, never the less, create the ad.**

Compare following screenshot to verify, that I have been able to create the ad:

![CreatedAnad](https://cloud.githubusercontent.com/assets/15871260/19471942/8663ef42-9525-11e6-969b-e57a4ee24d0e.jpeg)

**Comment by remoroethlisberger** [comment]
Bug is fixed on the master branch, check 0277994c8a001bd1e630fdf46ce8cf48c344514c .
