### ISSUE TITLE
Additional visual icon for premium users only

### ISSUE THREAD

**Issue by ghost** [scg-unibe-ch/ese2016-team8#10]
Premium users should have some sort of additional icon while beeing logged in, in order to show them that they are premium users. What is being proposed by the customer is to **add some sort of 'star' in the top bar** which is there for premium users (**but not 'normal' users**) and also **some sort of comment which says: "You are a premium user",** so that users won't get too confused.

**Comment by Dean442** [comment]
3d47bb8cdfd1329b3cbc4abdde53803fd40c2d21 All the premium users can now see a happy little star and a comment to award them for getting premium acces.
