### ISSUE TITLE
Premium Status not yet implemented

### ISSUE THREAD

**Issue by Dean442** [scg-unibe-ch/ese2016-team8#2]
We have to find a solution to giving a user premium status. 
Suggestion: adding a boolean to the user in database.

**Comment by Dean442** [comment]
the deed is done.

**Comment by remoroethlisberger** [comment]
When subscribing to the premium feature and after that immediately unsubscribing, I get the following error: 
![screenshot 2016-10-21 16 01 05](https://cloud.githubusercontent.com/assets/17845721/19601042/dac9f7b4-97a7-11e6-9995-3d9d418deb66.png)

**Comment by Dean442** [comment]
Problem was the name of the user and had nothing to do with the premium part.
