### ISSUE TITLE
[BUG] Something with the character set is wrong

### ISSUE THREAD

**Issue by remoroethlisberger** [scg-unibe-ch/ese2016-team8#3]
When trying to create an add with special characters, like ä,ö,ü they will become unreadable characters... I assume, that there is something wrong with the conversion between HTML input - Java - Database.

**Comment by remoroethlisberger** [comment]
![screenshot 2016-10-21 20 52 30](https://cloud.githubusercontent.com/assets/17845721/19608248/53ddd38c-97d0-11e6-9b2e-17efd09f98d3.png)

**Comment by javinator** [comment]
Issue fixed, Character Encoding Filter added to web.xml, look https://github.com/scg-unibe-ch/ese2016-team8/commit/39555347e6811bc37064f6b55b967d0675061dda
