### ISSUE TITLE
UI could use some work

### ISSUE THREAD

**Issue by ccorrodi** [scg-unibe-ch/ese2016-team8#31]
The UI is still rather simple (and close to what it was at the start of the project). Can you switch it up a bit?

**Comment by ghost** [comment]
As stated in the [8th documentation](https://github.com/scg-unibe-ch/ese2016-team8/blob/master/baseProject/Documentation/8th%20discussion.txt) further 'mockups'/ rework of the UI is optional and will only be graded as part of the presentation. It is not a native-requirement by the customer and therefure NO must.

Further changes to the UI will be discussed team-intern as it is yet to be decided whether we want/ need to redesign UI for the presentation. Therefore we consider this issue closed.

**Comment by ccorrodi** [comment]
Sounds good to me, but just in case this is not clear: You should present the real thing, not 'mockups' (you should present the latest and final release).

**Comment by ghost** [comment]
Great. Thanks for the further elaboration @ccorrodi !
