### ISSUE TITLE
Visiting times not working properly

### ISSUE THREAD

**Issue by ccorrodi** [scg-unibe-ch/ese2016-team8#34]
I can't edit an add and put up new visiting times. Sometimes nothing happens when saving, and sometimes I get a 500 Server Error due to some NullPointerException.

**Comment by remoroethlisberger** [comment]
Works fine for me, probably solved it with my last commit 8c2574e57e6183b67fbd620f7f2f03ec19c88885! :) So therefore the next official release, where this issue is fixed is in 2.2.1. Release date for 2.2.1 will be _14th of december_.
