### ISSUE TITLE
Alert earlier for Premium

### ISSUE THREAD

**Issue by ghost** [scg-unibe-ch/ese2016-team8#35]
Following the [requirements specification](https://github.com/scg-unibe-ch/ese2016/wiki/Project-Description) given initially, regarding the oncoming end of the project. 

The requirements, found at the last point as of 07.12.2016, splits itself up in two suppoints
- **Premium users** should receive alerts a bit **earlier**. 
- **Normal users** should receive alerts a bit **later**.

Both considered on a relative amount of time, so the implementation detail would be that the **premium user** get-notified **instantly** while the **non-premium user** will have a **delay**.

As no further documentation has been provided by the _authorities_, let's assume that it concers **every kind of alert**.

**Comment by remoroethlisberger** [comment]
This is implemented, check the following commit 175da4297ddfa09ed5970fa71406abcda51468ee 

The premium user are getting their alerts immediately and regular users will get the notification with a slight delay of 2 hours!
