### ISSUE TITLE
Date checker issue

### ISSUE THREAD

**Issue by javinator** [scg-unibe-ch/ese2016-team8#5]
Our date checker doesn't work correctly yet. I assume it checks only the day, not the entire date.
With dates as attached I get the error attached. (Tested with multiple combinations)

![date issue](https://cloud.githubusercontent.com/assets/22348463/19644429/e3c21942-99ef-11e6-8bc7-219980de74fb.png)
![date issue2](https://cloud.githubusercontent.com/assets/22348463/19644430/e722ff66-99ef-11e6-893a-6926eef9d1c6.png)

**Comment by remoroethlisberger** [comment]
There was an error in the comparison, instead of the dates it compared the strings lexicographically, which doesn't work with month endings and beginnings... check https://github.com/scg-unibe-ch/ese2016-team8/commit/c91f9e9f1b5d89dafef9ec471fcb35a7184ba925
