### ISSUE TITLE
Auction needs to be implemented properly

### ISSUE THREAD

**Issue by remoroethlisberger** [scg-unibe-ch/ese2016-team8#6]
Status report: Auction is somehow implemented, however we definitely need to decide on where to store the end date and how to inform the max bidder...
Also the "bid" process is not yet functional, there is a "bid button" implemented, which should take the value from it's input field right next to the button and save it inside the database. Note: It is not visible to the owner! However when bidding, the current price will be reset to 0 instead the new offer! I just tried to make a workaround, similar to the bookmark process...

**Comment by Dean442** [comment]
6c66ec242365d81ea50f97a8c0975132050c6545 is now possible and works fine.
what is left is to add a date when the auction ends, handle the function of the bid button if the auction is over and inform both highest bidder and owner of the ad.

**Comment by Dean442** [comment]
0500844b74f349c0ad5abce6838bdc35bc8207a4 Auction is now able to end and the bid button gets blocked if it is over. Still not able to display the highest bidder by name nor can it inform neither placer nor highest bidder of the add that it has ended.

**Comment by Dean442** [comment]
61b3601f851c4f1d125e8d6c004cb4d9ca62237d MaxBidder is now displayed and provided with a link to its profile.

**Comment by ghost** [comment]
Update: Following all the comments and commits, what remains to do is the [issue #7](https://github.com/scg-unibe-ch/ese2016-team8/issues/7), which is its own issue.
