### ISSUE TITLE
Send an e-mail when being overbid

### ISSUE THREAD

**Issue by ghost** [scg-unibe-ch/ese2016-team8#7]
Say we have user A and user B and an ad X which is an auction.

Now user A places a bid for the estate X. User A is now bidding the most (being the only one who bids).
Once user B **overbids** user A, user A should get notified with an e-mail sent to his personal e-mail address. 

This **e-mail** should contain basic information such as the **new price**, **the ad** itself and the **time remaining** when he has been overbidden.

**Comment by Dean442** [comment]
1420ccac60584a53d4b42a3e55727683d7e7b0de so far user A is contacted by user B that he no longer has the lead on the auction, via e-mail. so far I haven't found any option to let the system send it. Also up until now he only tells him on which ad he overbid him by the ad's name.
The new prize as well as the remaining time remain to be implemented.
