### ISSUE TITLE
Don't show roommates for an existing ad

### ISSUE THREAD

**Issue by ghost** [scg-unibe-ch/ese2016-team8#9]
While roommates can't be added when creating an add, compare issue https://github.com/scg-unibe-ch/ese2016-team8/issues/8, it is **no more needed to show the part with the roommates of the existing ad.**

**Comment by remoroethlisberger** [comment]
#01ef4fd70d2e9b72f3842239cea13a97a23ca2a4

**Comment by remoroethlisberger** [comment]
01ef4fd70d2e9b72f3842239cea13a97a23ca2a4 - done by @javinator
